apiVersion: apps/v1
kind: Deployment

metadata:
  name: vibelang-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vibelang

  template:
    metadata:
      labels:
        app: vibelang

    spec:
      containers:
      - name: vibelang-container
        image: vibelang-app
        ports:
        - containerPort: 5000